import { StyleSheet } from 'react-native';

import { calendarsUIColors } from '@constants/calendarsUI';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  scroll: { paddingBottom: 120 },
  headerBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: calendarsUIColors.surfaceHover,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCard: {
    padding: 16,
    paddingTop: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: calendarsUIColors.border,
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 14 },
  tile: {
    width: 56,
    height: 56,
    borderRadius: 16,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tileLetter: { fontSize: 26, fontWeight: '700' },
  headerInfo: { flex: 1, gap: 6 },
  headerName: {
    fontSize: 22,
    fontWeight: '700',
    color: calendarsUIColors.text,
    letterSpacing: -0.4,
  },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  metaText: { fontSize: 14, color: calendarsUIColors.textSecondary },
  metaOwnerName: { fontWeight: '600', color: calendarsUIColors.text },
  metaLink: { fontSize: 14, fontWeight: '600', color: calendarsUIColors.primary },
  descriptionBubble: {
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: calendarsUIColors.surfaceHover,
    borderRadius: 12,
  },
  descriptionText: { fontSize: 14, color: calendarsUIColors.textSecondary, lineHeight: 21 },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: calendarsUIColors.textMuted,
    letterSpacing: 0.3,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 8,
  },
  eventList: {
    marginHorizontal: 16,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: calendarsUIColors.border,
  },
  emptyEvents: {
    marginHorizontal: 16,
    padding: 24,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: calendarsUIColors.border,
    backgroundColor: calendarsUIColors.surface,
    alignItems: 'center',
  },
  emptyEventsText: { fontSize: 14, color: calendarsUIColors.textMuted, fontStyle: 'italic' },
  membersCard: {
    marginHorizontal: 16,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: calendarsUIColors.border,
    backgroundColor: calendarsUIColors.surface,
  },
  membersHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  membersHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  stackedAvatars: { flexDirection: 'row' },
  stackedAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stackedAvatarText: { fontSize: 11, fontWeight: '700' },
  membersHeaderLabel: { fontSize: 15, fontWeight: '500', color: calendarsUIColors.text },
  inviteBtn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    backgroundColor: calendarsUIColors.primaryLight,
  },
  inviteText: { fontSize: 14, fontWeight: '600', color: calendarsUIColors.primary },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 32,
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  headerSave: { paddingHorizontal: 18, paddingVertical: 8, borderRadius: 10 },
  headerSaveText: { fontSize: 14, fontWeight: '700' },
  editBody: { padding: 16, paddingTop: 20, gap: 16 },
  editTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: calendarsUIColors.text,
    textAlign: 'center',
  },
  previewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderRadius: 16,
    backgroundColor: calendarsUIColors.surface,
    borderWidth: 1,
    borderColor: calendarsUIColors.border,
  },
  previewTile: {
    width: 52,
    height: 52,
    borderRadius: 14,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewLetter: { fontSize: 24, fontWeight: '600' },
  previewName: { fontSize: 17, fontWeight: '600', letterSpacing: -0.2 },
  previewType: {
    fontSize: 13,
    color: calendarsUIColors.textMuted,
    marginTop: 2,
    textTransform: 'capitalize',
  },
  textInput: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: calendarsUIColors.border,
    backgroundColor: calendarsUIColors.surfaceHover,
    fontSize: 16,
    fontWeight: '500',
    color: calendarsUIColors.text,
  },
  textArea: { minHeight: 80, textAlignVertical: 'top', lineHeight: 22 },
  swatchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 12,
    backgroundColor: calendarsUIColors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: calendarsUIColors.border,
  },
  swatch: { width: 36, height: 36, borderRadius: 10 },
  swatchSelected: { borderWidth: 2.5, borderColor: '#FFFFFF' },
  dangerCard: {
    padding: 16,
    borderRadius: 14,
    backgroundColor: calendarsUIColors.dangerLight,
    borderWidth: 1,
    borderColor: '#FFD4D4',
  },
  dangerCopy: { fontSize: 13, color: '#CC4444', marginBottom: 12, lineHeight: 19 },
  dangerBtn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: calendarsUIColors.danger,
    alignItems: 'center',
  },
  dangerBtnText: { fontSize: 15, fontWeight: '700', color: '#FFFFFF' },
  testAffordance: { position: 'absolute', width: 1, height: 1, opacity: 0, top: 0, left: 0 },
  toast: {
    position: 'absolute',
    top: 16,
    left: 20,
    right: 20,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 6,
    zIndex: 100,
  },
  toastText: { fontSize: 15, fontWeight: '600', color: '#FFFFFF', textAlign: 'center' },
});
